apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yes-links

commonLabels:
  app.kubernetes.io/name: yes-links
  app.kubernetes.io/component: api

resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
